import getTheme from "@/utils/getTheme";
import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import React from "react";
import "../globals.css";
import { getLangDir } from "rtl-detect";
import Header from "@/components/header/Header";
import CustomCursor from "@/components/shared/CustomCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>;

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const theme = getTheme();
  console.log(theme);
  const dir = getLangDir(locale);
  const messages = await getMessages();

  return (
    <html dir={dir} lang={locale} className={theme ?? "dark"}>
      <body className="h-screen bg-background text-foreground scrollbar-thumb-muted scrollbar-thumb-rounded-md">
        <CookiesProvider>
          <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
            <CustomCursor />
          </NextIntlClientProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
